### ISSUE TITLE
Template-driven forms filesize and fileslimit validation not work as expect

### ISSUE THREAD

**Issue by acliyang** [pIvan/file-upload#1]
Hi, I test file-upload with template-driven forms, and it works. 
But it seemed validation not work. Below is my testing code:
`<form #demoForm="ngForm">
  <file-upload [(ngModel)]="uploadedFiles" [disabled]="false" [filesize]="100000" [fileslimit]="2" accept="audio/*" name="files"></file-upload>
</form>`

Whatever I select how big file, or many files, it not show error status.

**Comment by acliyang** [comment]
I found the class of file-upload is changed  to "ng-invalid" if I upload big file, so just set properly css then problem solved.

**Comment by pIvan** [comment]
Hi @acliyang,

it's exactly like you said file-upload element change class to ng-invalid, 
but if you want to access
error object in your component you can do something like this:

```
@ViewChild('demoForm') demoForm: NgForm;

public ngAfterViewInit(): void {
    this.demoForm.controls.uploadedFiles.errors // access errors list
}
```
