### ISSUE TITLE
Cannot find module 'google-code-prettify/bin/prettify.min.js'

### ISSUE THREAD

**Issue by lucky0007** [pIvan/file-upload#10]
Hi sir,

I am using this file upload in angular 7 when I am going to open my app it is showing Cannot find module 'google-code-prettify/bin/prettify.min.js' so how can i install this on node_module.

Thanks
Lokendra

**Comment by pIvan** [comment]
Hi @lucky0007,

can you explain me where and why are you using google-code-prettify? 
File upload module does not require google-code-prettify, 
that module is only used on demo page.

Kind regards,
Ivan

**Comment by pIvan** [comment]
Because there is no new info about this, and google-code-prettify is not
part of file-upload module, I'm closing this.
