### ISSUE TITLE
FormData is not defined

### ISSUE THREAD

**Issue by lynx-r** [pIvan/file-upload#11]
Hello, I am using your package with Angular Universal and I am getting an error: `FormData is not defined`

![telegram-cloud-file-2-257117167-43870--554554134172692992](https://user-images.githubusercontent.com/152172/53577623-09a5df00-3b87-11e9-9a2c-f4a64686c101.jpg)

Could you say how I can fix it?

**Comment by pIvan** [comment]
Hi @lynx-r,

I just made update which should fix problem with undefined FormData class.
Kind regards,

Ivan
