### ISSUE TITLE
'subscribe' of undefined

### ISSUE THREAD

**Issue by allahyar** [pIvan/file-upload#12]
I use ng serve --aot
![image](https://user-images.githubusercontent.com/12588629/54337056-f729ac00-4642-11e9-9d6a-20cb19bb498b.png)

**Comment by pIvan** [comment]
Hi @allahyar,

can You give me more info about your project?
How template in your component looks, and that part of component which is in relation
with file-upload?

Thanks,
Ivan

**Comment by allahyar** [comment]
Hi @pIvan 
Thanks for the fast answer 👍 
Look [here](https://stackblitz.com/edit/ngx-file-upload?file=src/app/app.component.ts)

**Comment by pIvan** [comment]
1. If you want to use component with angular reactive form, then you should write it this way

`<file-upload simple [formControl]="fileControl">` 
**or** `<file-upload simple formControlName="controlName">`

2. If you want to use it with template driven form

`<file-upload simple [(ngModel)]="files">`

3. and if you want to use it without angular form

import { Component,OnInit } from '@angular/core';
import { FileUploadValidators, FileUploadControl } from '@iplab/ngx-file-upload';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent {
    private fileControl = new FileUploadControl(FileUploadValidators.filesLimit(1));
}

`<file-upload simple [control]="fileControl">`

**Comment by allahyar** [comment]
I have this problem too :(
![image](https://user-images.githubusercontent.com/12588629/54473874-e3bd4300-47f2-11e9-91c6-9d9002645907.png)
