### ISSUE TITLE
Issue with accept user input.

### ISSUE THREAD

**Issue by dmytrodemchenko** [pIvan/file-upload#15]
It allows to put any type of files and it seems that it doesn't work properly.

Also, when I use image/* pattern - it shows all visible files in a folder instead of https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_accept

```javascript
<file-upload ngModel accept="file_extension|audio/*|video/*|image/*|media_type" name="files"></file-upload>
```

**Comment by dmytrodemchenko** [comment]
Why you didn't bind user inputs with an HTML template?

**Comment by pIvan** [comment]
It is same as file limitation, validator should only validate values and
prepare error objects, you can use them to show user which files are allowed

**Comment by dmytrodemchenko** [comment]
Probably, you are not right.
Have you seen the example https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_accept ? 

Accept uses for avoiding unnecessary files for uploading, also it helps to user pick up the right format file  from the bunch of files - and it works properly in an example above.

**Comment by pIvan** [comment]
You're right. Thank's @dmytrodemchenko beacuse you have noticed it. 
Should be implemented in the next few days

**Comment by dmytrodemchenko** [comment]
I do not use accept attr as a validator - the main idea to clean a folder from unnecessary files as it provided by official docs. 

Everything that you need to do:

```hml
 <input #inputRef type="file" **[accept]='acceptInput'** class="files-input" tabindex="-1" multiple (change)="onInputChange($event)">
```

Please let me know what do you think about this?

**Comment by dmytrodemchenko** [comment]
@pIvan thank you a lot for your collaboration.

**Comment by pIvan** [comment]
Support for native accept attribute was added.

It is possible to use it as attribute on `<file-upload accept="..."> || <file-upload [accept]="...">`
or if you use `FileUploadControl` as  `FileUploadControl.acceptFiles(...string)`.

**Comment by pIvan** [comment]
I guess we can close this.

**Comment by dmytrodemchenko** [comment]
@pIvan thank you a lot for that!
