### ISSUE TITLE
[Feat] Directive for text "Drag and drop..."

### ISSUE THREAD

**Issue by Rapiiidooo** [pIvan/file-upload#17]
I think it would be a good idea to add two directives to let user change the text showed in the upload-text. (Necessary for language translation)

I mean one directive as : 
textStrong: with default would be "Drag and drop files"
text: with default would be "or click here"

**Comment by pIvan** [comment]
Hi @Rapiiidooo,

To simplify code in **file-upload,** it is possible to change whole template which will show text, 
and in that template you can use l10n.
For that purpose in your project you can create component which will be wrapper for file-upload.


`<file-upload>`
`<ng-template let-isFileDragDropAvailable="isFileDragDropAvailable" #placeholder>`
`<span *ngIf="isFileDragDropAvailable">drop or click</span>`
`<span *ngIf="!isFileDragDropAvailable">click</span>`
`</ng-template>`
`</file-upload> `

**Comment by Rapiiidooo** [comment]
Nice !

Working perfectly 👍 .

Then I think you should notice it on documentation :) ! Unless I'm just blind I could not find out.

Thank you @pIvan

**Comment by pIvan** [comment]
You can find it here [documentation](https://pivan.github.io/file-upload/) 
under section **Custom templates**.

You're welcome @Rapiiidooo
