### ISSUE TITLE
File type is empty => accept validation failed

### ISSUE THREAD

**Issue by greenwenny** [pIvan/file-upload#18]
Hello,

sometimes (Chrome on Windows) the filetype can not be determined. Especially with Microsoft files (word, excel). Therefore my accept type validation fails.

![UploadValidationFails](https://user-images.githubusercontent.com/50322079/57222982-dbb89d00-7004-11e9-93a3-988b87ae9daa.PNG)

**Comment by pIvan** [comment]
Hi @greenwenny,
Fix will be ready in the next few days, thank you.
