### ISSUE TITLE
How to avoid uploading file having size 0 bytes

### ISSUE THREAD

**Issue by sharmaguides** [pIvan/file-upload#2]
Is there a method which can be used to avoid file having the size of 0 byte

**Comment by pIvan** [comment]
Hi @sharmaguides 

for now if you use both ways, reactive or template driven
it is not possible to do so unless you make you'r own directive or validator

But if you can wait, I will add them today during the day.

**Comment by pIvan** [comment]
Now it's possible to validate is file size in range (exclusive).
**Template**
`<file-upload ngModel [minsize]="20" [maxsize]="10000" name="files"></file-upload>`
`<file-upload ngModel minsize="20" maxsize="10000" name="files"></file-upload>`
**Reactive**
`FileUploadValidators.sizeRange({ minSize?, maxSize? })`

A library is transferred to new location [@iplab/ngx-file-upload](https://www.npmjs.com/package/@iplab/ngx-file-upload)

**Comment by sharmaguides** [comment]
Thank you @pIvan

**Comment by pIvan** [comment]
You're welcome @sharmaguides
