### ISSUE TITLE
Custom templates

### ISSUE THREAD

**Issue by DamianAllende** [pIvan/file-upload#20]
Hi, I'm new to Angular,
In its Custom templates component, I would like to know how span works since when loading my image the first span does not disappear, it is always visible and the second span never appears.

`<ng-template let-isFileDragDropAvailable="isFileDragDropAvailable" #placeholder>
                    <span *ngIf="isFileDragDropAvailable">drop or click</span>
                    <span *ngIf="!isFileDragDropAvailable">click</span>
                </ng-template>`

Best regards, I hope you have given me to understand my English is somewhat limited

**Comment by pIvan** [comment]
Hi @DamianAllende,

those span elements depend on that does browser support drag and drop natively
or not, so if you're browser support drag and drop you'll see only first span.
If you want to define span position when list is visible, you can use
css class names on his parent element **file-upload** which are added if
there is any file in it

has files and list is visible
```
<file-upload class="has-files list-visible">
<span>
</file-upload>
```

has files but list is not visible
```
<file-upload class="">
<span>
</file-upload>
```

no files
```
<file-upload class="">
<span>
</file-upload>
```


Kind regards,
Ivan
