### ISSUE TITLE
extension name ignore case

### ISSUE THREAD

**Issue by cannon021** [pIvan/file-upload#23]
could check extension name ignore case ?

**Comment by pIvan** [comment]
Hi @cannon021, I don't think I fully understood the question,
could you give me some example?
Should ignore case be applied to validation or?

**Comment by cannon021** [comment]
ignore case differences when comparing filenames

like the code below
==============================================================
/**
 * function used to check file type
 * 
 * #### allowedTypes
 * file_extension|audio/*|video/*|image/*|media_type
 */
const checkFileType = (file: File, allowedTypes: Array<string>): ValidationErrors | null => {
    // convert to lowCase
    const fileExtension = file.name.split('.').pop().trim().toLocaleLowerCase();
    const fileType = getFileType(file, fileExtension);

    for (const type of allowedTypes ) {
        const isValid = FILE_EXT_REG.test(type) ? type.toLocaleLowerCase() === `.${fileExtension}` : new RegExp(type).test(fileType);
        if (isValid) {
            return null;
        }
    }

    return {allowedTypes, actual: file.type, file};
};
