### ISSUE TITLE
how about export FileUploadService ？

### ISSUE THREAD

**Issue by cannon021** [pIvan/file-upload#26]
If you open FileUploadService, it is convenient to read when the file size exceeds the limit.

for example:  `actual : 10240(byte)`   `display: 10K`

**Comment by pIvan** [comment]
Idea is to have file upload library as simple as can be and to retain abstraction,
if I export class used just as helper inside component somebody else can ask to
implement some method convenient for his project, and there can be millions of such
requests.

Easily you can write validation or in this case function which can be used as
you want, and where you want.
For now, I don't see needs for exporting this service.
