### ISSUE TITLE
Drag and drop limit to 1 file

### ISSUE THREAD

**Issue by invaderb** [pIvan/file-upload#28]
greetings, this is a really awesome module, however I have one issue/ request.

In the documentation I see 
`<file-upload ngModel fileslimit="2" name="files"></file-upload>`

But it doesn't seem to be limiting the number of files that can be added to the list.

Here is a snippet of my code am I doing something wrong?
`<file-upload [(ngModel)]="blast.file" name="file" (ngModelChange)="onFileEmmit(blast.file)" animation="false" accept=".xlsx" fileslimit="1" required></file-upload>`

**Comment by pIvan** [comment]
Hi @invaderb,

fileslimit is just validator on FileUpload component, if you want to disable drop zone after
one file is uploaded,
You can make some changes and use custom template and/or disableing whole component once user drop one file.

exc.
```
this.filesControl.valueChanges.subscribe(() => 
... if(this.filesControl.value.length == 0) this.filesControl.enable() 
else this.filesControl.disable()
);
```

**Comment by invaderb** [comment]
That worked perfectly thank you!

**Comment by pIvan** [comment]
You're welcome!
