### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to load because no supported source was found.

### ISSUE THREAD

**Issue by nikhilrajnair** [pIvan/file-upload#30]
When i uploading the 3gpp/x-flv files this error shows

**Comment by pIvan** [comment]
Hi @nikhilrajnair can you provide me more info?
Like, is that happening on demo page? Code example?
Thanks

**Comment by nikhilrajnair** [comment]
If i am uploading mp4 file it works fine ,When i uploading the 3gpp/x-flv files shows the error



> Hi @nikhilrajnair can you provide me more info?
> Like, is that happening on demo page? Code example?
> Thanks

**Comment by nikhilrajnair** [comment]
it's regarding the `HTML5` video player issue , i used [video.js](https://github.com/videojs/videojs-flash) for playing the flv videos.
