### ISSUE TITLE
FileUploadValidators.filesLimit()

### ISSUE THREAD

**Issue by avssolutions** [pIvan/file-upload#33]
FileUploadValidators.filesLimit() does not work you can select multi files in dragandrop

**Comment by pIvan** [comment]
Hi @avssolutions,
please can you check [issue #28](https://github.com/pIvan/file-upload/issues/28).

Kind regards,
Ivan

**Comment by avssolutions** [comment]
Hello @pIvan ,  the problem is next, i try to select just one file, not drag and drop, i can select multiple, even i  have made FileUploadValidators.filesLimit(1), because I see in template input with attribute multiple i need to remove that multiple. I am using reactive forms
Thanks

**Comment by pIvan** [comment]
so you want to use <file-upload> not <file-upload simple> to select only one file?

**Comment by avssolutions** [comment]
I need when someone want to not drag and drop, he just click on area, to be able to select only one file, not multiple

**Comment by pIvan** [comment]
Ok @avssolutions I'll mark this as an enhancement 
because this wasn't a plan to implement. Will be done in the next few days
