### ISSUE TITLE
Multiple=false still allows mulitple files via drag&drop

### ISSUE THREAD

**Issue by jerone** [pIvan/file-upload#35]
When I have `[multiple]="false"` it is possible to drag and drop multiple files.
![afbeelding](https://user-images.githubusercontent.com/55841/77199703-905a9080-6ae9-11ea-8543-7338674ec4c7.png)

The file-dialog correctly only allows one file.

---

_Version 1.5.0, because version 2.0.0 doesn't work for Angular 8._

**Comment by pIvan** [comment]
Hi @jerone,
a lot of people have been looking for this functionality so I will implement it,
even though it was only validation until now.

**Comment by pIvan** [comment]
Constraint multiple is enabled on v1.5.1 and 2.0.1

**Comment by jerone** [comment]
Awesome work! I'll apply this tomorrow.

**Comment by pIvan** [comment]
Thanks :)

**Comment by jerone** [comment]
I tested it, and works great!
