### ISSUE TITLE
how use validate

### ISSUE THREAD

**Issue by MHKarami97** [pIvan/file-upload#37]
Can we show errors if errors? for example if file size is more than valid size. like this:

`            <div class="col-sm-12">
              <div class="form-group">
                <label for="userId" class="label">img</label>
                <file-upload [(ngModel)]="uploadedFiles" #fileInput="ngModel" name="files" fileslimit="1" accept=".jpg, .png, .jpeg" maxsize="10 MB" multiple="false" required>
                   <ng-template let-isFileDragDropAvailable="isFileDragDropAvailable" #placeholder>
                     <span *ngIf="isFileDragDropAvailable">click</span>
                     <span *ngIf="!isFileDragDropAvailable">click</span>
                   </ng-template>
                </file-upload>
                <ng-container *ngIf="fileInput.invalid && fileInput.touched">
                  <p class="caption status-danger" *ngIf="fileInput.errors?.required">
                    required
                  </p>
                  <p class="caption status-danger" *ngIf="fileInput.errors?.pattern">
                    not valid
                  </p>
                </ng-container>
              </div>
            </div>`

**Comment by pIvan** [comment]
Hi @MHKarami97,

if you look at the source of each of the validators,
you will see objects they create as errors.

accept = [fileInput.errors?.fileTypes](https://github.com/pIvan/file-upload/blob/0d715bb6e15d79e82959f5bc81970a0852bb81e4/projects/iplab/ngx-file-upload/src/lib/helpers/validators.class.ts#L139)

filesize = [fileInput.errors?.sizeRange](https://github.com/pIvan/file-upload/blob/0d715bb6e15d79e82959f5bc81970a0852bb81e4/projects/iplab/ngx-file-upload/src/lib/helpers/validators.class.ts#L94)

fileslimit = [fileInput.errors?.filesLimit](https://github.com/pIvan/file-upload/blob/0d715bb6e15d79e82959f5bc81970a0852bb81e4/projects/iplab/ngx-file-upload/src/lib/helpers/validators.class.ts#L109)

Kind regards,
Ivan
