### ISSUE TITLE
How to clear the list after successfull image uploads?

### ISSUE THREAD

**Issue by Zeshan316** [pIvan/file-upload#4]
Hello
I am facing some issue that how to clear the list when image uploaded to the server. Nothing found special in the documentation for this example. Using angular template driven forms.

**Comment by pIvan** [comment]
Hi @Zeshan316,

bug has fixed and documentation page is updated.
Also you can compare code change [1f47712](https://github.com/pIvan/file-upload/commit/1f47712fd47795e3e6667e75d72424f2f3a0b659)

and download last version from [@iplab/ngx-file-upload](https://www.npmjs.com/package/@iplab/ngx-file-upload) 

kind regards,
@pIvan

**Comment by Zeshan316** [comment]
That's good.

I've checked docs there is some bug. The selected files are not showing in dropzone.

**Comment by pIvan** [comment]
Thanks @Zeshan316,

there was problem in demo page build task, all should be fixed.

**Comment by Zeshan316** [comment]
Thanks, working fine.
