### ISSUE TITLE
template design equal to default

### ISSUE THREAD

**Issue by poderosoans** [pIvan/file-upload#40]
Is it possible to have the same design that comes by default and only change the text to another language?
It is difficult for me to get the same design with the templates 
http://prntscr.com/sdiapq

Thanks

**Comment by pIvan** [comment]
Hi @poderosoans,

currently, it is not possible, but it will be next week.
Thanks!

**Comment by poderosoans** [comment]
Thank you

**Comment by pIvan** [comment]
Default templates are exported so you can localize text in them, an example is available [here ](https://pivan.github.io/file-upload/#template-reuse)
