### ISSUE TITLE
Cannot set maxsize

### ISSUE THREAD

**Issue by BorisZubchenko** [pIvan/file-upload#44]
![image](https://user-images.githubusercontent.com/31354262/84673698-bbab1b00-af32-11ea-99f1-d75a06e512b3.png)

As you can see, I cannot bind maxsize to the component.
Moreover, there is no compile error due to attribute binding, but it appears when one-way binding.

Seems like it doesn't work (I've just printed `control.getError().flat()[0]`):
![image](https://user-images.githubusercontent.com/31354262/84674958-493b3a80-af34-11ea-9976-d8faa041e9ac.png)

**Comment by pIvan** [comment]
Hi @BorisZubchenko, directive as maxsize exactly is used with angular template-driven form,
in you're case you have FileUploadControl instance binded through control property,
that allows you to set any custom validator without of HTML element attributes.
Same is with multiple and accept.

Kind regards

**Comment by BorisZubchenko** [comment]
Oh, my bad, I provided `10 * Math.sqrt(1024)` to the validator thinking that I'm doing `10 * 1024 * 1024` (that's where 320 came from). I thought it's the default value. I have to get some sleep :)  
I'm sorry. Anyway, thank you for your response!

**Comment by pIvan** [comment]
Yeah, sometimes we need to sleep :P
