### ISSUE TITLE
Customize text of file-upload-drop-zone

### ISSUE THREAD

**Issue by StalinMazaEpn** [pIvan/file-upload#47]
Hello,

Is there any plan to add a property to the component to can customize the text that will be displayed on the drop zone area. For example to show the text in another language like that:

> <file-upload dropZoneText="Arrastra y suelta los archivos o haz click aquí"></file-upload>

Thanks!

**Comment by pIvan** [comment]
Hi @StalinMazaEpn,

the same request was mentioned in this [issue](https://pivan.github.io/file-upload/#template-reuse).

Kind regards,
Ivan

**Comment by StalinMazaEpn** [comment]
Thanks @pIvan 👍😁
