### ISSUE TITLE
Wrong file  when drag and drop

### ISSUE THREAD

**Issue by yoedusvany** [pIvan/file-upload#49]
I'm using angular 10, when I drag and drop into the component a pdf file for example, don't show me any error and let me "adjunt" the file. In the next code I pass some parameters to the original component

` <app-custom-upload id="otherPics"
                                               [accept]="'.jpeg,.jpg,.png'"
                                               [formGroup]="profileForm"
                                               [formName]="'otherPics'"
                                               [multipleFiles]="true"
                            >
                            </app-custom-upload>`

Here the original component

`<file-upload [formControlName]="formName"
                 [multiple]="multipleFiles"
                 [accept]="accept"
    >`

Any idea?

**Comment by pIvan** [comment]
Hi, @yoedusvany can you prepare some demo, 
or at least give me more code from that some app-custom-upload component?

**Comment by yoedusvany** [comment]
Here is the code, is a base component for "adjunt" images files in some cases and in other cases pdf.

`<div *ngIf="!formEvents" [formGroup]="formGroup">
    <file-upload [formControlName]="formName"
                 [multiple]="multipleFiles"
                 class="upload-file-text-profile"
                 [accept]="accept"
                 [ngClass]=" small? 'upload-file-btn-small' : 'upload-file-btn-profile'"
    >
        <ng-template let-file="file" let-isFileDragDropAvailable="true" #placeholder>
            <ng-container class="upload-file-text-profile" *ngIf="file; else emptyList">
                {{ file.name }}
            </ng-container>

            <ng-template #emptyList>
                <div class="text-upload" *ngIf="!rider">
                    {{ "REGISTER.DRAG_IMAGE" | translate}}
                </div>
                <div class="text-upload" *ngIf="rider">
                    {{"REGISTER.DRAG_FILE" | translate}}
                </div>
                <div class="btn-default btn-upload">
                    {{"REGISTER.SELECT_FILE" | translate}}
                </div>
            </ng-template>
        </ng-template>
    </file-upload>
</div>`

And the ts, I pass some Input vars

`export class CustomUploadComponent implements OnInit, OnChanges {
    @Input() formName: FileUploadControl;
    @Input() formGroup: FormGroup;
    @Input() model: NgModel;
    @Input() rider?: boolean;
    @Input() small?: boolean;
    @Input() accept?: string;
    @Input() formEvents = false;
    @Input() multipleFiles = false;

    constructor() {}
    ngOnInit(): void {
    }
    ngOnChanges(changes: SimpleChanges): void {}
    clear() {}
}`

Important here are accept where I pass formats permited, but when I drag and drop break the validations.

**Comment by pIvan** [comment]
I did a speed test according to your code and everything looks ok to me.
Did I do anything different from you?

[component](https://ibb.co/NgRBSWT)
[ui](https://ibb.co/g7vcDNH)
[debug - console](https://ibb.co/74znmcN)
[debug - html](https://ibb.co/3zVjHDM)
[html](https://ibb.co/FsbtRqq)

**Comment by yoedusvany** [comment]
Ohooo, form status is the key mmm. But  Is there any way to avoid to
"adjunt" the wrong file?

**Comment by pIvan** [comment]
How each input on form does not have any restriction, and by html specification [accpet](https://html.spec.whatwg.org/multipage/input.html#attr-input-accept) attribute provide user agents with a **hint** of what file types will be accepted.
Same is with file size limitation, that is something what should be validated before sending, but how You're not the first who asked about this, I'll add that functionality in future as something like **discard atribute/method**

**Comment by yoedusvany** [comment]
Ok Ivan, thanks a lot for your responses, I hope you can do it. By the way,
good work with the package!!!!

Regards Yoedusvany.

**Comment by pIvan** [comment]
Thanks, @yoedusvany, I'll try to make changes as soon as I can! :)

**Comment by pIvan** [comment]
Hi @yoedusvany,

support for discarding invalid files was added, please check [discard section](https://pivan.github.io/file-upload/#discard)
