### ISSUE TITLE
When I Submit button click then server response each and every time getting blank data in this file upload

### ISSUE THREAD

**Issue by mithlesh20apr** [pIvan/file-upload#5]

**Comment by pIvan** [comment]
Hi @mithlesh20apr,

can you provide me more info about problem, 
how you're client côde look, and how back-end côde look?

**Comment by mithlesh20apr** [comment]
Thanks, For response @pIvan 

This one is my reactive form group code
      public fileUploadControl = new FileUploadControl(FileUploadValidators.fileSize(80000));
      public fileUploadWithTemplate = new FileUploadControl();
      public filesControl = new FormControl(null, FileUploadValidators.accept(['video/*', 'image/*', '.mp3']));

   // Article form validations
        this.articleForm = this._fb.group({
          uploadFiles: [null],
          feature_image:[null]
     });
    public uploadedFiles = [];
    public isDisabled: boolean = false;
  get uploadFiles() {
    return this.articleForm.get('uploadFiles');
  }
  get feature_image() {
    return this.articleForm.get('feature_image');
  }
And sumbit form this code

  // submit to the api

  submitForm() {
   console.log(this.articleForm);
   let headers = new Headers({ "content-type": "application/json" });
   let options = new RequestOptions({ headers: headers });
   this.http.post("http://localhost:7001/api/v1/article/createarticle/", JSON.stringify(this.articleForm.value), options)
      .map(result => result.json())
      .subscribe(data => {
    //articleForm = data;
    console.log(data);
  }, error => {
    console.log("Oooops!" + error);
  });
  
  }
 
Backend code is 

This file is commonMiddleware files

const multer = require('multer');
var path = require('path');
exports.uploadFiles = function (req, res, next) {
  try{ 
 var storage = multer.diskStorage({
        destination: function (req, file, cb) { 
            cb(null,  __basedir + '../uploads/');
        },
    filename: function (req, file, cb) { 
        console.log("file in filename ",file);
        file.uploaded_name = Date.now() + file.originalname.replace(/ /g, "_").toLowerCase();
        var file_name=Date.now() + file.originalname.replace(/ /g, "_").toLowerCase();
        // if(file.fieldname && file.fieldname=="avatar"){
        //    file.avater_url = 'http://localhost:7001/'  + './public/images/uploads/' + file_name;
        // }
      
        const ext = file.mimetype.split('/')[1];
        next(null, file.fieldname + '-' + Date.now() + '.'+ext);      
        cb(null, file_name);
        return
        },
        filename: function (req, file, callback) {
            callback(null,  file.fieldname + '-' + Date.now()  + path.extname(file.originalname));
             console.log('hi');
        }
    }); 
    var upload = multer({
    "storage": storage,
    fileFilter: function (req, file, cb) {
        var ext=path.extname(file.originalname);
        if(file.fieldname && (file.fieldname=="uploadFiles" || file.fieldname=="feature_image")){
            var validExtensions = ['.jpg','.png','.jpeg',".gif",".JPG",".PNG",".JPEG",".GIF"];
            if (validExtensions.indexOf(ext) < 0) {
              return cb(new Error('Allowed image extentions are jpg,png,jpeg and gif'))
            }
        }
        if(file.fieldname && file.fieldname=="cv"){
            var validExtensions = [".pdf", ".doc", ".docx"];
            if (validExtensions.indexOf(ext) < 0) {
              return cb(new Error('Allowed CV extentions are pdf,doc and docx'))
            }
        }
        cb(null, true)
   } 

}).fields([ 
            { name: 'uploadFiles', maxCount: 10 },
            {name: 'feature_image', maxCount:1}
           
        ])
  }catch(err){
        res.send({status: false, message: 'Somethingh went wrong '+err,data:{}});
    }
};

And this one is my controller page

var restify = require('restify');
var articleModel = require('mongoose').model('articleModel');

exports.createArticle = function (req, res, next) {
 //  console.log(req.files.article_upload.name);
    var articleData = req.body;
    var files = req.files;
    console.log(files);
    console.log('Creating Article Data with', articleData);
    var new_user = new articleModel({
         files: req.files
        // otherfiles: req.files
    });
    new_user.save(function(err){
      if(err) console.log('dd' + err); 
    });
    // log applicationForm
    console.log(JSON.stringify(new_user, null, 4));
     res.send(new_user);
}
// This function gets the details of Articles
exports.getArticle = function (req, res, next){
    var cursor = articleModel;
    if (!cursor){
        return next(new restify.errors.InternalServerError('Model instance(s) is not defined'));
    }
    else{
        cursor.find(function(err, objs){
            if (err) {
                return next(new restify.errors.InternalServerError(err));
            } else {
                res.status(200);
                res.send({"result":objs});
            }
        });
    }    
}

When I submit button click then controller page given me each and every time ("files": [],) blank array.

**Comment by pIvan** [comment]
@mithlesh20apr 
can you confirm me that this client side côde is sending the File list to controller?

 **is here everything ok with data?**
```
submitForm() {
   console.log(this.articleForm);
```

**content-type should be multipart/form-data; not application/json**
```
let headers = new Headers({ "content-type": "application/json" });
let options = new RequestOptions({ headers: headers });
this.http.post("http://localhost:7001/api/v1/article/createarticle/", JSON.stringify(this.articleForm.value), options)
```
check file upload example on [developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications#Asynchronously_handling_the_file_upload_process)

**Comment by mithlesh20apr** [comment]
submitForm() {
   console.log(this.articleForm);

Yes this code is given me all right data including with files

**Comment by pIvan** [comment]
@mithlesh20apr that mean how component works fine,
to fix you're problem please check content-type and mentioned link,
I hope how that would be helpful

**Comment by pIvan** [comment]
Did these materials help you with your problem?

**Comment by pIvan** [comment]
I'm closing this because a problem is not connected with component.

**Comment by biggosh** [comment]
I found the same problem. The only way to solve the problem for me was to transform the template form data (I used template forms) to FormData object. 

I tried to set the content-type but it was not enough.

On my opinion HttpClient.post does not manage correctly the files object.

I hope this can help somebody.

**Comment by pIvan** [comment]
Hi @biggosh, yes,
to upload files you need to use FormData and change content-type.
Thank You for pointing this out!
