### ISSUE TITLE
peer dependency warning when using Angular 10

### ISSUE THREAD

**Issue by yuchaosydney** [pIvan/file-upload#50]
When upgrading Angular 9 to Angular 10, got warning message:

`Package "@iplab/ngx-file-upload" has an incompatible peer dependency to "@angular/animations" (requires "^9.0.0 | ^10.0.0", would install "10.1.2").`

**Comment by yuchaosydney** [comment]
Duplicate issue 46

**Comment by pIvan** [comment]
Hi @yuchaosydney last version (2.0.8) should support @angular v10
