### ISSUE TITLE
iplab-ngx-file-upload.d.ts has no selector, please add it!

### ISSUE THREAD

**Issue by CryHenry** [pIvan/file-upload#51]
Great Module. Works well...except...

I can debug, but when trying to build for production I get this error...

ERROR in Directive ɵa in D:/xampp7/htdocs/varive.app/node_modules/@iplab/ngx-file-upload/iplab-ngx-file-upload.d.ts has no selector, please add it!
Cannot determine the module for class ɵa in D:/xampp7/htdocs/varive.app/node_modules/@iplab/ngx-file-upload/iplab-ngx-file-upload.d.ts! Add ɵa to the NgModule to fix it.

**Comment by CryHenry** [comment]
For those who come after me...I am using Angular 8 and seems rolling back to version 1.5.3 of the ngx-file-upload has solved the issue.

**Comment by pIvan** [comment]
Hi, @CryHenry on which version you had an issue with the selector?

**Comment by CryHenry** [comment]
Hi mate,

V2.0.4 had the issue for me running under Angular 8.

**Comment by pIvan** [comment]
Yes version 2.0.0 is compatible with angular 9.0.0 || 10.0.0 || 11.0.0, for older version as you mentioned angular 8 it is 1.0.0

Thanks, @CryHenry for pointing that out
