### ISSUE TITLE
not triggering change event on drop files

### ISSUE THREAD

**Issue by sidjai09** [pIvan/file-upload#54]
I want to call function on every change ether for selecting in input or by dropping file in file-upload

**Comment by pIvan** [comment]
Hi @sidjai09,

which event? valueChanges, statusChanged or some other?

**Comment by sidjai09** [comment]
valueChanges event is not calling function on drop file.

**Comment by sidjai09** [comment]
Hii @pIvan 

I am using following versions,
Node :- 14.14.0
npm :- 6.14.8
Angular version :- 10.1.7
 
 HTML:-
<file-upload
        [(ngModel)]="uploadedFiles"
        [multiple]="true"
        (valueChanges)="onFileInputChange()"
        (change)="onFileInputChange()"
        [control]="fileUploadControl"
        id="files"
        name="files"
>

TS:-
onFileInputChange() {
       .... do something
}

**Comment by pIvan** [comment]
valueChanges is emitted only when the value has been changed (either on input change or dropping files),
there is no event that is called only on file drop.

So you have control `fileUploadControl`, you are able to listen value change on it,
so you don't need any event or property configuration over HTML template.

`fileUploadControl.valueChanges.subscribe((newValue) => )`

**Comment by sidjai09** [comment]
Thank you @pIvan
It works...

I was unaware about this syntax.

**Comment by sidjai09** [comment]
@pIvan 
Just a kind suggestion show this syntax in Document so other can find it easily

**Comment by pIvan** [comment]
There is but without all events [demo](https://pivan.github.io/file-upload/#stand-alone),
methods explanation is on the bottom of the page.
:)
