### ISSUE TITLE
Number of files limit

### ISSUE THREAD

**Issue by antonioadami** [pIvan/file-upload#55]
Hello, it would be great if we could limit the number of files in the layout, not just on "FileUploadValidators.filesLimit(1)"

**Comment by pIvan** [comment]
Hi @antonioadami,

can you explain to me how would you limit them? If you place FileUploadValidators.filesLimit(1)
validator and enable [discard](https://pivan.github.io/file-upload/#discard) you'll get the layout limitation.
Is that something that you expect to have?

Kind regards,
Ivan

**Comment by antonioadami** [comment]
Hi @pIvan ,

Searching deeper on the documentation I found out that I could just disable multiple. That solved my issue. Thanks.
