### ISSUE TITLE
Error in ng build --prod

### ISSUE THREAD

**Issue by arkabhowmick** [pIvan/file-upload#59]
`Directive ɵa in /node_modules/@iplab/ngx-file-upload/iplab-ngx-file-upload.d.ts has no selector, please add it!`
Hi, I am getting the above issue while doing a ng build prod.
Is there any solution for this ?
I am on angular 8.1.3
I am on version : "2.0.9"

**Comment by pIvan** [comment]
Hi @arkabhowmick, 1.5.0 is the last version compatible with angular 8.x.x

**Comment by arkabhowmick** [comment]
Ah.. thanks.. it's working
