### ISSUE TITLE
Cannot be used in any other module except root module

### ISSUE THREAD

**Issue by dzonatan** [pIvan/file-upload#6]
Importing `FileUploadModule` in any other module than root results in error:
`Error: BrowserModule has already been loaded`.

You might want to have `FileUploadModule` included only in one of your lazy-loaded modules, not in the entire app.

And this is happening because of `BrowserAnimationsModule` import:
https://github.com/pIvan/file-upload/blob/cc672f3d2c7a28a365775cf8bee43dc5ab1c1bd2/src/lib/file-upload.module.ts#L30

That's bad. This module should not be imported in any library - it has to be left for the developers to decide if they want animations it their apps or not.

Just mention about animations somewhere like in `readme.md` as other packages do:
https://material.angular.io/guide/getting-started#step-2-configure-animations

**Comment by pIvan** [comment]
Hi @dzonatan,
you're right, I'm working on a fix.

**Comment by pIvan** [comment]
`BrowserAnimationsModule` is excluded from the library, what should 
resolve the problem.

As you mentioned the animation is now optional, 
also demo page is updated to explain how to do so.

**Comment by glynmercieca** [comment]
> `BrowserAnimationsModule` is excluded from the library, what should
> resolve the problem.
> 
> As you mentioned the animation is now optional,
> also demo page is updated to explain how to do so.

How do i remove/disable animations? could not find reference in demo page

**Comment by pIvan** [comment]
Hi @glynmercieca 

it is simple, just use **NoopAnimationsModule** instead BrowserAnimationsModule,
check [installation section](https://pivan.github.io/file-upload/#installation) 
```
import {NoopAnimationsModule} from '@angular/platform-browser/animations';

@NgModule({
    imports: [
        BrowserModule,
        ...
        FileUploadModule,
         NoopAnimationsModule
    ],
    bootstrap: [AppComponent]
})
export class AppModule {}

```

**Comment by glynmercieca** [comment]
Ok, but is there a way to only disable the animations just in this component, as I need the browser animations in the app in general

**Comment by pIvan** [comment]
Currently, there isn't possible to disable animation, but I have in plan to
implement module configuration in the next two days.

someting like this:
`FileUploadModule.withConfig({ disableAnimations: true }),`

**Comment by pIvan** [comment]
@glynmercieca there is new version 1.3.0
where you can disable animation on certain component,
with adding animation="false" attribute on it.
The demo page has been updated to.
