### ISSUE TITLE
Attribute option with multiple image preview 

### ISSUE THREAD

**Issue by cybernize** [pIvan/file-upload#61]
Hi,
Can I use the attribute component option and preview multiple images?

eg: -
`      <div #dropZone file-drop-zone [control]="control">
           <div>
               some content
           </div>
           <div *ngIf="control.size > 0">
                <div class="upload-wrapper">
                    <div class="thumbnail-container" *ngFor="let file of dropZone.control.value; let i = index">
                        <span class="delete-button" (click)="control.removeFile(file)"> X
                        </span>
                        <img [src]="uploadedFile | async">
                     </div>
                </div>
            </div> 
     </div>
`

**Comment by pIvan** [comment]
Hi @cybernize,

I'm afraid I didn't quite understand the question. 
If you ask if you can preview the image, yes it is possible, for that use [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsArrayBuffer).

**Comment by cybernize** [comment]
Hi,
I want to show thumbnails of the dropped files(images). How can I iterate that in template as shown above. For instance I can iterate file name with "file.name"

**Comment by pIvan** [comment]
`&lt;div #dropZone file-drop-zone [control]="control"&gt;
	&lt;div&gt;some content</div&gt;
	&lt;div *ngIf="control.size > 0"&gt;
		&lt;div class="upload-wrapper"&gt;
			&lt;div class="thumbnail-container" *ngFor="let file of dropZone.control.value; let i = index"&gt;
				&lt;span class="delete-button" (click)="control.removeFile(file)"&gt; X &lt;/span&gt;
				&lt;img [src]="readFile(file) | async" /&gt;
			&lt;/div&gt;
		&lt;/div&gt;
	&lt;/div&gt;
&lt;/div&gt;`

and method in component class

`
public async readFile(file: File): Promise<string> {
		return new Promise(done => {
			const reader = new FileReader();
			reader.onload = () => done(reader.result)
			reader .readAsArrayBuffer(file);
		});
	}
`

And please, in the future don’t open issue for something that isn’t a problem. 
Please read the JavaScript API documentation yourself.

Kind regards,
Ivan
