### ISSUE TITLE
Create a reject function in validators

### ISSUE THREAD

**Issue by alexqbm** [pIvan/file-upload#63]
Right now we can use `FileUploadValidators.accept(['.zip', '.jpeg'])` to specify which file extensions to accept in the component. However, having the opposite, a **reject** function that would expect only those file extensions that are not accepted, would be very useful.

**Comment by pIvan** [comment]
Hi @alexqbm,
it is possible to write your own validator for each case, so too for this one. 
I will add it in a next release, because I also think it is something frequently used.

Thanks @alexqbm.

**Comment by alexqbm** [comment]
That'll be great! Looking forward for that. Thanks, Iván 😃

**Comment by alexqbm** [comment]
Btw Iván, where could I check how to create custom validators as you mentioned? It is exactly what I need right now but there is no info about it in https://pivan.github.io/file-upload/

**Comment by pIvan** [comment]
Can you tell me which layout do you use? Standalone, ng reactive form.?..

**Comment by alexqbm** [comment]
Sure! I am currently using the standalone one.

**Comment by pIvan** [comment]
```
import { ValidatorFn, ValidationErrors  } from '@iplab/ngx-file-upload';

public fileUploadControl = new FileUploadControl(null, [FileUploadValidators.fileSize(80000), this.rejectValidator(['.zip', '.jpeg'])]);

private rejectValidator(rejectFileTypes: Array<string>): ValidatorFn {
        return (control: AbstractControl | FileUploadControl): ValidationErrors => {
            const files: Array<File> = control.value;

            if (IsNullOrEmpty(files)) { return null; }

            const rejectedFiles = files.map((file) => checkFileType(file, allowedFileTypes))
                                        .filter((error) => error);

            return rejectedFiles.length > 0 ?
                {'rejectedTypes': rejectedFiles} : null;
        };
}
```

method rejectValidator can be implemented similar to [accept](https://github.com/pIvan/file-upload/blob/f067e38965d7cacf900d1e6caed8a6cb96dfdf14/projects/iplab/ngx-file-upload/src/lib/helpers/validators.class.ts#L136)

**Comment by alexqbm** [comment]
I see it clear now, thanks!

However, this approach allows us to specify the input right from the declaration of the fileUploadControl. How could we implement a reject/function that relied on the file information itself? Let's say: how could we create a function that rejected files based on their filename?

**Comment by alexqbm** [comment]
Thank you for your time, Iván. It is clear to me now.

Keep up the good work! I'll be recommending your project to any Angular developer that asks me for a file uploading solution :)

**Comment by pIvan** [comment]
Thanks @alexqbm,

if you want to discard invalid, you need to tell that to component ;)
Component by default accept all, and just validate his content, so if you want you can show that error, or
if you want to discard invalid files, just use this flag in constructor discardInvalid: true.

```
public readonly control = new FileUploadControl({ discardInvalid: true },
        [FileUploadValidators.filesLimit(10), ...validators]
);
```

Also make sure your validator returns list of files which need to be removed as follows

```
return rejectedFiles.length > 0 ?
                {'rejectedTypes': Array<File>} : null;
```
