### ISSUE TITLE
File upload icon does not align correctly when adding files to template-driven file-upload component.

### ISSUE THREAD

**Issue by Riuen** [pIvan/file-upload#64]
There seems to be an issue when using the file upload component in a template-driven form. 

**HTML**
```<file-upload [(ngModel)]="source" name="files" (ngModelChange)="onChange($event)" #fileComp></file-upload>```

When the variable called "source" is empty then the file upload component displays the default "Drag and drop files or click here"message along with the file upload icon. However, once I programmatically populate the variable then the default message goes away but the file upload icon is still left in the center of the component.

**Screenshots**
![fileupload_no_files](https://user-images.githubusercontent.com/17307281/144114454-c86629a5-235a-40f2-a8bd-1ecae0c97fb9.png)

![fileupload_w_files](https://user-images.githubusercontent.com/17307281/144114764-ebe1a67d-c3da-4d5b-b93f-b559780815ab.png)

**Expected Behaviour**
File upload icon should be aligned to the top right corner of the component.

Angular Version: 12.2.9
ngx-file-upload version: 3.3.1

**Comment by pIvan** [comment]
Hi @Riuen,

please check css definition, that part is hidden with selector:

```
.list-visible .upload-text {
    display: none;
}
```
