### ISSUE TITLE
Do we have feature to hide/disable the remove icon from each file upload item list? 

### ISSUE THREAD

**Issue by sumitdhungana14** [pIvan/file-upload#66]
I want to show the remove icon on the file item i.e. `<file-upload-item-list>` only on certain conditions and hide/disable on other conditions. Is there a property exposed by `<file-upload>` component I could bind to to achieve this requirement?

**Comment by pIvan** [comment]
Hi @sumitdhungana14,

the component is designed so that it is possible to customize the list,
the built-in list is as it is and the parameters will not hide the icons,
you can  create your own custom list.
