### ISSUE TITLE
Weird Issue with ngx-sortablejs

### ISSUE THREAD

**Issue by BAHTechPlasma** [pIvan/file-upload#69]
It seems that when I add your file upload component to my form, it also seems to break the sortable nature of [ngx-sortablejs](https://github.com/SortableJS/ngx-sortablejs) without causing any console errors. Don't really have time to look into it right now, but will update if I figure out the conflict.

**Comment by pIvan** [comment]
Hi @BAHTechPlasma,
have you been able to determine what the problem is?

**Comment by pIvan** [comment]
closed due to inactivity
