### ISSUE TITLE
Peer dep resolution

### ISSUE THREAD

**Issue by toastyghost** [pIvan/file-upload#70]
Would it be possible to publish some 1.5.x with in-between versions of Angular? We're migrating incrementally and currently on 9, and getting npm install errors with both 1.5.4 and 4.0.x:

![with-1 5 4](https://user-images.githubusercontent.com/204219/170714443-f99d3534-6fd3-49bf-bec5-0551e259a221.png)
![with-4 0 1](https://user-images.githubusercontent.com/204219/170714439-bd0076a3-e562-45b2-82e0-ee1973d8cbcf.png)

Or if there is another way to resolve this, please let me know

**Comment by pIvan** [comment]
Hi @toastyghost I'll add it later today

**Comment by toastyghost** [comment]
That's awesome, thank you for responding so quickly!

**Comment by pIvan** [comment]
Hi @toastyghost can you try with latest 1.5.x version? It should work without problems with the angular 9

**Comment by pIvan** [comment]
The package should be compatible with versions up to angular 12, if you need 13 there is the latest version 2.x.x.
Can you try version 1.5.x now?

**Comment by pIvan** [comment]
Hi @toastyghost thanks for the snippet which has a problem, I will try it today

**Comment by pIvan** [comment]
Hi @toastyghost , versions 11, 12, 13 and 14.0.0 are out!
Will this be enough?

**Comment by pIvan** [comment]
version 2.0.8 is compatible with 9 and 10. I have to work hard to separate and prepare this as versions 11, 12, 13 and 14. All because of a bug in the npm package manager.
Can you update projects to angular 11 or higher to skip angular 9?

**Comment by toastyghost** [comment]
Still having to use `--legacy-peer-deps` as a workaround, unfortunately.
