### ISSUE TITLE
Detect Event when delete element 

### ISSUE THREAD

**Issue by joseserrano15** [pIvan/file-upload#74]
How can I detect when an element from the list is deleted? or when the span is clicked?  I Use template-driven form

![image](https://user-images.githubusercontent.com/68348356/178319929-6ba2bedb-f8bd-46f9-904c-0dc28ee29819.png)

**Comment by pIvan** [comment]
Hi @joseserrano15, 

currently that is not possible if you use angular template-driven form, 
but it can be if you use it with FileUpload Control instance.
Here is example of it.

class:
`public readonly fileUploadControl = new FileUploadControl();

constructor() {
    this.fileUploadControl.discardedValueChanges.subscribe((files: File[]) => { console.log(`deleted files:`, files) })
}
`

html:
`<file-upload [(ngModel)]="fieldName" [control]="customFileUploadControl"></file-upload>`

**Comment by joseserrano15** [comment]
It worked perfectly! Thank you.
