### ISSUE TITLE
Angular 15 support

### ISSUE THREAD

**Issue by jerone** [pIvan/file-upload#75]
Will this package support Angular 15.

**Comment by pIvan** [comment]
Done :)

**Comment by jerone** [comment]
Thanks @pIvan 👍

For future references: https://github.com/pIvan/file-upload/commit/41b101b3d0106ce3e5307983e3cf8c5d1eb72add

It looks like the readme is forgotten: https://github.com/pIvan/file-upload/blob/master/README.md?plain=1#L26

It's not clear from the readme if this package is backwards compatible. Can I use version 15 of this package with Angular 14 (while I wait for other packages to upgrade)?

**Comment by pIvan** [comment]
Hi @jerone,

I wrote a readme but for some reason I forgot to push it,
you can use version 15 but with flag --force because peerDeps
are fixed for each version of angular package
