### ISSUE TITLE
Feature request: file extension

### ISSUE THREAD

**Issue by jasperwauters** [pIvan/file-upload#76]
It would be great if there was an option to only allow files with a certain extension. 

In my case I only want to allow my user to upload a CSV-file.

**Comment by pIvan** [comment]
Hi @jasperwauters, library already have this feature.
You can check [demo](https://pivan.github.io/file-upload/#discard), discardInvalid is a property you
need, or if you don't want to discard what user has added to upload, you can use just validator.
