### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by Bilelkabtni** [pIvan/file-upload#77]
While tracking issues created by Sentry, I noticed this issue while removing an uploaded image 
![Screenshot 2023-02-27 at 14 53 37](https://user-images.githubusercontent.com/12344704/221582129-20ce8cc1-cace-4bae-ad22-94e23723fdbc.png)

how to solve this issue? thanks

**Comment by pIvan** [comment]
Hi @Bilelkabtni,

can you give me more info about that issue. Like which version of file-uplaod is used,
also from where method removeFile() was called? Also why is called with argument file which is undefined 
instead File object?

Thanks, @pIvan

**Comment by Bilelkabtni** [comment]
@pIvan HI thanks for your quick reply, 

- package version: 15.0.0
-  I think the line that cause the issue was here [removeFile](https://github.com/pIvan/file-upload/blob/f067e38965d7cacf900d1e6caed8a6cb96dfdf14/projects/iplab/ngx-file-upload/src/lib/helpers/control.class.ts#L104) maybe, in this case, were the file object is not set better to throw an error?

**Comment by pIvan** [comment]
@Bilelkabtni it is not crucial, I'll fix it next week, thanks! :)
