### ISSUE TITLE
Setting Multiple to false is not working

### ISSUE THREAD

**Issue by mattiLeBlanc** [pIvan/file-upload#78]
Hi,

I am trying to set Multiple to false but the value is not accepted via the configuration:

```  
public fileUploadControl = new FileUploadControl({
    multiple: false,
    accept: ['text/csv'],
  }, FileUploadValidators.fileSize(3000000));
```
The control still allows multiples.
It only works using an attribute, which is fine be me:
```
<file-upload [control]="fileUploadControl" multiple="false">
```

**Comment by pIvan** [comment]
Hi @mattiLeBlanc, will be fixed this week
