### ISSUE TITLE
TypeValidator filetype sometimes failed on windows

### ISSUE THREAD

**Issue by Noppey** [pIvan/file-upload#8]
Hi,

When I use validation of fileType and I run the code in Chrome or IE on Windows, it doesn't always accept my types.

This occurs for allowedTypes[] of ['.csv', '.xls', '.xlsx'] and with combinations of xlsx and csv files that I try to upload.

**Comment by pIvan** [comment]
Hi @Noppey,
thank You.

Problem will be corrected as soon as possible.

**Comment by Noppey** [comment]
Hi, it seems to be working now, thanks for the quick solution!

You only forgot to remove the console.log of notallowedfiles, so this shows up every file upload now :)

**Comment by pIvan** [comment]
Thanks @Noppey, I'll remove it today :)
