### ISSUE TITLE
File upload list item  - error

### ISSUE THREAD

**Issue by Banditzx** [pIvan/file-upload#91]
Hello.

In new version 19.0.1

```
Element implicitly has an 'any' type because expression of type 'unique symbol' can't be used to index type 'Signal<number>'.
  Property '["@angular/core".ɵINPUT_SIGNAL_BRAND_WRITE_TYPE]' does not exist on type 'Signal<number>'
```

```
Element implicitly has an 'any' type because expression of type 'unique symbol' can't be used to index type 'Signal<File>'.
  Property '["@angular/core".ɵINPUT_SIGNAL_BRAND_WRITE_TYPE]' does not exist on type 'Signal<File>'.
```

```
Element implicitly has an 'any' type because expression of type 'unique symbol' can't be used to index type 'Signal<FileUploadControl>'.
  Property '["@angular/core".ɵINPUT_SIGNAL_BRAND_WRITE_TYPE]' does not exist on type 'Signal<FileUploadControl>'.
```

When I upgraded to a new version, my code returned an error.  The parameters started to give an error
`<file-upload-list-item [index]="i" [file]="file" [control]="control">Remove</file-upload-list-item>`

**Comment by pIvan** [comment]
Hi @Banditzx, can you provide more details? Do you have an ng-template around it? How do you define the index, file, and control variables in the template? In version 19, I converted all input annotations to signals.

**Comment by Banditzx** [comment]
> Hi @Banditzx, can you provide more details? Do you have an ng-template around it? How do you define the index, file, and control variables in the template? In version 19, I converted all input annotations to signals.

![Code_MkCKbdCtZe](https://github.com/user-attachments/assets/f139b490-dd81-47e6-a9de-874d37d716ad)

**Comment by pIvan** [comment]
Can you try the latest version 19.0.3?

**Comment by Banditzx** [comment]
> Can you try the latest version 19.0.3?

I am using the latest version of angular 19.0.1 as of today.  And Angular Language Service for vscode 19.0.3 version.  But the error does not go away.

![Code_h1PradAlYP](https://github.com/user-attachments/assets/7c6cf04f-596d-48bd-9619-49beec136fb5)

**Comment by pIvan** [comment]
Did you tried with @iplab/file-upload@19.0.3?

**Comment by Banditzx** [comment]
> Did you tried with @iplab/file-upload@19.0.3?

Where I can try 19.0.3? On the [npm](https://www.npmjs.com/package/@iplab/ngx-file-upload?activeTab=readme) I can see only 19.0.2 last version

**Comment by pIvan** [comment]
Sorry, my mistake, the latest version is 19.0.2. If it doesn't work, I'll set up a demo environment today and try to fix it.

**Comment by Banditzx** [comment]
> Sorry, my mistake, the latest version is 19.0.2. If it doesn't work, I'll set up a demo environment today and try to fix it. Demo page is same as your code but with new control flow, and it works

Thank you. I'll be waiting

**Comment by pIvan** [comment]
Can you provide more details about your package.json (TypeScript, angular...) and angular.json files, specifically regarding the builder configuration?

**Comment by Banditzx** [comment]
> Can you provide more details about your package.json (TypeScript, angular...) and angular.json files, specifically regarding the builder configuration?

yeap.
Attached:
[angular.json](https://github.com/user-attachments/files/17990063/angular.json)
[package.json](https://github.com/user-attachments/files/17990065/package.json)

**Comment by Banditzx** [comment]
> I can't reproduce the error. I made some changes to the signatures of the fields mentioned as errors. Could I ask you to try the latest version? Also, if you can reproduce the issue on a test project, I would kindly ask you to send it to me so I can check what's going on. Thank you!

I don't know what you did. But it's fixed issue. Look at this
![Code_lrfPPSnked](https://github.com/user-attachments/assets/78c64ba1-fb6c-4c97-92f4-e51ae30c0d37)
![chrome_7rchtumdIC](https://github.com/user-attachments/assets/645a89e5-c673-45db-a957-7fd4c066f8eb)
Is work!

**Comment by Banditzx** [comment]
Thank you for fix issue!
